config/routes.rb
Annatunes::Application.routes.draw do
  match 'home',    :to => 'pages#home'
  match 'about',   :to => 'pages#about'
  match 'contact', :to => 'pages#contact'
  match 'help',    :to => 'pages#help'

  root :to => 'pages#home'

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
    @title = "Home"
  end

  def contact
    @title = "Contact"
  end

  def about
    @title = "About"
  end

  def help
    @title = "Help"
  end
end

app/helpers/application_helper.rb
module ApplicationHelper

  def logo
    image_tag("logo.png", :alt => "AnnaTunes Logo")
  end

  # Return a title on a per-page basis
  def title
    base_title = "AnnaTunes"
    if @title.nil?
      base_title
    else
      "#{@title} | #{base_title}"
    end
  end

end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/layouts/_footer.haml
%footer
  %nav
    %ul
      %li= link_to "About", about_path
      %li= link_to "Contact", contact_path
      %li= link_to "News", '#'

app/views/layouts/_header.haml
%header
  = link_to logo, root_path
  %nav
    %ul
      %li= link_to "Home", root_path
      %li= link_to "Help", help_path
      %li= link_to "Login", '#'

app/views/layouts/_javascripts.html.haml
= javascript_include_tag "application"

app/views/layouts/_stylesheets.html.haml
= stylesheet_link_tag    "blueprint/screen", :media => "screen"
= stylesheet_link_tag    "blueprint/print",  :media => "print"
/[if lt IE 8]
  = stylesheet_link_tag  "blueprint/ie",     :media => "all"
= stylesheet_link_tag    "application",      :media => "all"

app/views/layouts/application.html.haml
!!! 5
%html
  %head
    %title= title
    = render 'layouts/stylesheets'
    = render 'layouts/javascripts'
    = csrf_meta_tags

  %body.container
    = render 'layouts/header'
    %section
      = yield
    = render 'layouts/footer'

app/views/pages/about.html.haml
%h1 About Us
%p
  AnnaTunes helps Catholic musicians discover, track, and share musical pieces for Mass.

app/views/pages/contact.html.haml
%h1 Contact
%p
  AnnaTunes is a two-person project in the earliest phases of development.

  %div{:itemscope => true, :itemtype => "http://www.schema.org/Person"}
    %div{:itemprop => "name"}
      %span{:itemprop => "givenName"} Cody
      %span{:itemprop => "additionalName"} A.
      %span{:itemprop => "familyName"} Ray

    %div{:itemprop => "jobTitle"} The Developer
    %a{:itemprop => "email", :href => "mailto:talktome@codyaray.com"} talktome@codyaray.com
    %a{:itemprop => "url",   :href => "http://codyaray.com"} codyaray.com

  %div{:itemscope => true, :itemtype => "http://www.schema.org/Person"}
    %div{:itemprop => "name"}
      %span{:itemprop => "givenName"} Anna
      %span{:itemprop => "familyName"} Dron
    %div{:itemprop => "jobTitle"} The Inspiration
    %a{:itemprop => "email", :href => "mailto:anna@prettynerd.com"} anna@prettynerd.com
    %a{:itemprop => "url",:href =>"http://prettynerd.com"} prettynerd.com

app/views/pages/help.html.haml
%h1 Help
%p Get help on AnnaTunes.

app/views/pages/home.html.haml
%h1 AnnaTunes
%p
  This is the home page for AnnaTunes

= link_to "Sign up now!", '#', :class => "signup_button"